# Generated by Django 5.0.7 on 2024-07-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_team_members_alter_teammembership_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("slug", models.SlugField(max_length=64)),
                ("content", models.TextField()),
            ],
        ),
    ]
