# Generated by Django 5.0.7 on 2024-07-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
