# Generated by Django 5.0.7 on 2024-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_contentfile_remove_submission_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentfile",
            name="file",
            field=models.FileField(upload_to="content-files/%Y/%m/%d/"),
        ),
    ]
