# Generated by Django 5.0.7 on 2024-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_page_mimetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="mimetype",
            field=models.CharField(
                choices=[("text/markdown", "Markdown"), ("text/html", "Html")],
                default="text/markdown",
                help_text="Mimetype used to render this page",
                max_length=32,
            ),
        ),
    ]
