# Generated by Django 5.1.2 on 2024-10-12 14:27

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_submission_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", django_jsonform.models.fields.JSONField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "get_latest_by": "date_created",
            },
        ),
        migrations.RemoveField(
            model_name="submission",
            name="gh_repo",
        ),
        migrations.AddField(
            model_name="submission",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
