# Generated by Django 5.1.2 on 2024-10-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_submissionmetadata_remove_submission_gh_repo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="description",
        ),
        migrations.RemoveField(
            model_name="version",
            name="name",
        ),
        migrations.AddField(
            model_name="submission",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="version",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="version",
            name="filename",
            field=models.CharField(default="test.txt", max_length=1024),
            preserve_default=False,
        ),
    ]
