# Generated by Django 5.1.2 on 2024-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_remove_version_description_remove_version_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionmetadata",
            name="instructions",
            field=models.TextField(default="Submission requirements: lorem ipsum"),
            preserve_default=False,
        ),
    ]
