# Generated by Django 5.0.7 on 2024-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_page_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_home",
            field=models.BooleanField(default=False),
        ),
    ]
