# Generated by Django 5.0.7 on 2024-08-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_page_is_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(help_text="Markdown specifying the page's content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_home",
            field=models.BooleanField(
                default=False,
                help_text="Use current page as the home page. Only one page can have this enabled at any given time",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="order",
            field=models.IntegerField(
                help_text="Ordering of this page on the navbar", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                help_text="Slug used to refer to this page's URL", max_length=128
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.CharField(max_length=2048)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="web.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="submission",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.project",
            ),
        ),
    ]
