# Generated by Django 5.0.7 on 2024-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_alter_page_content_alter_page_is_home_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug used to refer to this image", max_length=128
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="submission",
            name="project",
        ),
    ]
