# Generated by Django 5.0.7 on 2024-09-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_alter_page_mimetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentfile",
            name="slug",
            field=models.SlugField(
                help_text="Slug used to refer to this image",
                max_length=128,
                unique=True,
            ),
        ),
    ]
