# Generated by Django 5.0.7 on 2024-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_alter_contentfile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="header_content",
            field=models.TextField(
                blank=True, help_text="Content to use as page header", null=True
            ),
        ),
    ]
