# Generated by Django 5.0.7 on 2024-11-04 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_alter_evaluation_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="toc_accepted",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="version",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="web.submission",
            ),
        ),
    ]
