# Generated by Django 5.1.2 on 2024-11-05 00:16
# Hand edited by Yuvi to be a rename

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0027_submission_toc_accepted_alter_version_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="order",
            new_name="navbar_order"
        ),
    ]
