# Generated by Django 5.1.2 on 2024-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_remove_page_order_page_navbar_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="navbar_order",
            field=models.IntegerField(
                blank=True,
                help_text="Ordering of this page on the navbar. Leave unset to hide from navbar",
                null=True,
                unique=True,
            ),
        ),
    ]
