# Generated by Django 5.1.2 on 2024-11-22 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_remove_submission_team_remove_teammembership_team_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collaborators",
            new_name="Collaborator",
        ),
    ]
