# Generated by Django 5.1.2 on 2024-11-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_remove_evaluation_evaluator_logs_collaborators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="team",
        ),
        migrations.RemoveField(
            model_name="teammembership",
            name="team",
        ),
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="teammembership",
            name="user",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamMembership",
        ),
    ]
