# Generated by Django 5.1.2 on 2024-11-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0034_evaluation_evaluator_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=models.TextField(),
        ),
    ]
